[package]
name = "typer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glutin = "0.30.0"
raw-window-handle = "0.5.0"

[build-dependencies]
gl_generator = "0.14"

